'''
Unit tests for crontab._pausedLines, the line selection behind
pauseCaptureJobs()/resumeCaptureJobs() (see PAUSABLE_JOB_SUBSTRINGS): the capture job
and the watchdog are paused, other jobs are not. No real crontab is involved; the
read/write I/O is not tested.
'''

from frankAllSkyCam import crontab


def test_comments_out_the_regular_capture_line():
    lines = ["*/1 6-20 * * * python3 -m frankAllSkyCam >log/capture.log 2>&1 #frankAllSkyCam-managed\n"]

    result = crontab._pausedLines(lines)

    assert result == ["#*/1 6-20 * * * python3 -m frankAllSkyCam >log/capture.log 2>&1 #frankAllSkyCam-managed\n"]


def test_comments_out_the_watchdog_line():
    lines = ["*/15 * * * * python3 -m frankAllSkyCam.watchDog >log/watchdog.log 2>&1 #frankAllSkyCam-managed\n"]

    result = crontab._pausedLines(lines)

    assert result[0].startswith("#")


def test_leaves_other_managed_jobs_running():
    # startrail, timelapse, cleanup, calculateEphem and generateExtraData don't use the
    # camera or watch for capture staleness, so none of them is touched
    lines = [
        "50 7 * * * python3 -m frankAllSkyCam.startrail >log/startrail.log 2>&1 #frankAllSkyCam-managed\n",
        "0 8 * * * python3 -m frankAllSkyCam.timelapse >log/timelapse.log 2>&1 #frankAllSkyCam-managed\n",
        "0 1 * * * python3 -m frankAllSkyCam.allskycamdelete >log/allskycamdelete.log 2>&1 #frankAllSkyCam-managed\n",
        "0 */6 * * * python3 -m frankAllSkyCam.calculateEphem >log/calculateEphem.log 2>&1 #frankAllSkyCam-managed\n",
        "*/5 * * * * python3 /home/pi/frankAllSkyCam/tools/generateExtraData.py >log/generateExtraData.log 2>&1 #frankAllSkyCam-managed\n",
    ]

    result = crontab._pausedLines(lines)

    assert result == lines


def test_leaves_unrelated_user_cron_entries_untouched():
    lines = ["0 3 * * * /home/pi/my_own_backup_script.sh\n"]

    result = crontab._pausedLines(lines)

    assert result == lines


def test_does_not_double_comment_an_already_paused_line():
    lines = ["#*/1 6-20 * * * python3 -m frankAllSkyCam >log/capture.log 2>&1 #frankAllSkyCam-managed\n"]

    result = crontab._pausedLines(lines)

    assert result == lines


def test_realistic_mixed_crontab_only_pauses_the_two_camera_jobs():
    lines = [
        "#Crontab generated by frankAllSkyCam #frankAllSkyCam-managed\n",
        "*/1 6-20 * * * python3 -m frankAllSkyCam >log/capture.log 2>&1 #frankAllSkyCam-managed\n",
        "*/2 21-23 * * * python3 -m frankAllSkyCam >log/capture.log 2>&1 #frankAllSkyCam-managed\n",
        "*/15 * * * * python3 -m frankAllSkyCam.watchDog >log/watchdog.log 2>&1 #frankAllSkyCam-managed\n",
        "50 7 * * * python3 -m frankAllSkyCam.startrail >log/startrail.log 2>&1 #frankAllSkyCam-managed\n",
        "0 3 * * * /home/pi/unrelated_personal_job.sh\n",
    ]

    result = crontab._pausedLines(lines)

    assert result[0] == lines[0]  # header comment, never touched (already starts with #)
    assert result[1].startswith("#") and "python3 -m frankAllSkyCam >" in result[1]
    assert result[2].startswith("#") and "python3 -m frankAllSkyCam >" in result[2]
    assert result[3].startswith("#") and "-m frankAllSkyCam.watchDog" in result[3]
    assert result[4] == lines[4]  # startrail: untouched
    assert result[5] == lines[5]  # unrelated user job: untouched
